version: "3.8"

services:
  flask:
    build: flask
    environment:
      - BACKEND_HOST=bottle
      - BACKEND_PORT=8080
    networks:
      - frontend
    ports:
      - 8888:8888

  bottle:
    build: bottle
    environment:
      - REDIS_HOST=redis
    networks:
      - frontend
      - backend

  redis:
    image: redis:6.0.9-alpine
    networks:
      - backend

networks:
  frontend:
  backend:
