version: "3.8"

services:
  bottle:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
    networks:
      - demo
    ports:
      - 8080:8080
  
  redis:
    image: redis:6.0.9-alpine
    networks:
      - demo

networks:
  demo:
