apiVersion: apps/v1
kind: Deployment
metadata:
  name: bottle
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bottle
  template:
    metadata:
      labels:
        app: bottle
    spec:
      containers:
        - name: bottle
          image: tomowatt/python-bottle-demo:latest
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
