---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: ghcr.io/tomowatt/flask
          imagePullPolicy: Always 
          env:
            - name: BACKEND_HOST
              value: bottle-cluster-ip
            - name: BACKEND_PORT
              value: '8080'
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 8888
